### ISSUE TITLE
Add stairs support

### ISSUE THREAD

**Issue by mrkn** [red-data-tools/unicode_plot.rb#17]

**Comment by nanobowers** [comment]
@mrkn  
A direct port of julia code here:
https://github.com/nanobowers/unicode_plot.rb/blob/new_features/lib/unicode_plot/stairs.rb
I have validated the operation with some example code, but have not added tests yet.

This update is mingled with some other bug-fixes and support for block canvas, **please let me know if you want separate PRs for each feature/issue**.

**Comment by mrkn** [comment]
Could you make a pull-request to add  your implementation?

**Comment by mrkn** [comment]
This is fixed by #38.
