### ISSUE TITLE
Add stemplot support

### ISSUE THREAD

**Issue by mrkn** [red-data-tools/unicode_plot.rb#30]
I'd like to support stemplot.
The example implementation is available in the proposal to UnicodePlot.jl at https://github.com/Evizero/UnicodePlots.jl/pull/69

**Comment by nanobowers** [comment]
@mrkn 
I can look at the adding stemplot support if it is not already being worked on.

**Comment by mrkn** [comment]
I haven't touched this issue yet.  It is very helpful.

**Comment by mrkn** [comment]
This is resolved. Thank you @nanobowers!
