### ISSUE TITLE
How about raising an ArgumentError when the border is unknown?

### ISSUE THREAD

**Issue by kojix2** [red-data-tools/unicode_plot.rb#41]
```ruby
require 'unicode_plot'

x = 0.step(3*Math::PI, by: 3*Math::PI / 30)
y_sin = x.map {|xi| Math.sin(xi) }
UnicodePlot.lineplot(x, y_sin, border: :stripe).render # Unknown border type
```

Expected behavior

`raise ArgumentError, "unknown border type: #{border_type}"`

Current behavior

```
undefined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by kojix2** [comment]
I thought about sending a pull request, but I didn't know where to put the `raise`.

**Comment by mrkn** [comment]
@kojix2 Do you want only an appropriate exception?  Don't you need to access the list of border types like #42?

**Comment by kojix2** [comment]
Just checking whether a border is available can help you understand the error message.
Of course, having a list of borders is more useful.
