### ISSUE TITLE
Write barplot documents

### ISSUE THREAD

**Issue by mrkn** [red-data-tools/unicode_plot.rb#5]

**Comment by nanobowers** [comment]
Hello @mrkn , do you have a preference for how to provide documentation for this issue and #6 ?  
Is the intent to enhance the README.md to look more like https://github.com/Evizero/UnicodePlots.jl/blob/master/README.md  ?
Or do you propose to add RDoc/YARD compatible documentation to the code itself?
Or create a Wiki to this repo with a page for each plot type?

**Comment by mrkn** [comment]
I guess starting from the reference manual in YARD format is good for this library.
And, it is good that we can provide many use cases in example codes.

I don't know GitHub Wiki is an appropriate space to provide a user guide.
