### ISSUE TITLE
Anti-Aliasing

### ISSUE THREAD

**Issue by obromios** [red-data-tools/unicode_plot.rb#58]
First, thank you for a very useful utility.

Have you thought about [anti-aliasing](https://www.hp.com/us-en/shop/tech-takes/what-is-anti-aliasing) the plot.  It may, in some circumstances, make the plots easier to interpret?

**Comment by kojix2** [comment]
Let's try [cool-retro-term](https://github.com/Swordfish90/cool-retro-term)!
I really like this terminal emulator. Fantastic anti-aliasing.

![image](https://user-images.githubusercontent.com/5798442/124922256-470eb700-e034-11eb-9a49-18400c79414e.png)
Joking aside, I don't think anti-aliasing is a issue that can be controlled by UnicodePlot. That's the job of the terminal emulator. Please find your favorite terminal emulator that allows anti-aliasing and set it up.

**Comment by mrkn** [comment]
@obromios What did you mean by "anti-aliasing" in this context?  I couldn't imagine what the result you want because UnicodePlot just makes a plot result by filling Unicode characters while anti-aliasing is a technique for altering a bitmap image.

Could you describe it by illustrating both before and after outcomes if the "anti-aliasing" were supported?

**Comment by obromios** [comment]
@mrkn, anti-aliasing is a general term referring to correction of signals being reconstructed at too low a sampling rate. You are correct that in image processing, the most common way to do this is altering the bit map image.  However, I was wondering whether anyone had done some thinking about this for this gem. In particular with the full unicode character set, you have characters like the [spacing modifier letters](https://en.wikipedia.org/wiki/Spacing_Modifier_Letters), that might allow you to do some rough anti-aliasing.  It may well be an up hill task, but I will put this on my list of things to think about.

**Comment by mrkn** [comment]
@obromios I'm interested in how to perform anti-aliasing with spacing modifier letters. UnicodePlot is designed for using monospace characters to build rectangle canvas to show in a terminal so I consider surrogate pairs etc. are not usable. I would like to see more detail example. Could you illustrate how to use such special letters?

By the way, if you want to get more higher resolution plots, you can specify a larger canvas size by passing `width` and `height` parameter like:

```
UnicodePlot.lineplot(x, y_sin, name: "sin(x)", width: 200, height: 50)
```

<img width="1300" alt="Screen Shot 2021-07-19 at 16 03 57" src="https://user-images.githubusercontent.com/3959/126117166-03c60aa4-839e-4430-97ce-a43bf8c00931.png">
